version: "2"
linters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/trmlabs/starrocks-profile-collector
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
